name: unit_test

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
            make build_test

      - name: run
        run: |
            make run_test
